// Enhanced Field Officers with ratings and workload
export const fieldOfficers = [
  {
    id: "4",
    full_name: "Sarah Williams",
    role: "field_officer",
    email: "sarah@example.com",
    notification_enabled: true,
    points: 650,
    language_preference: "en",
    created_at: "2024-01-20T11:00:00Z",
    rating: 4.8,
    active_workload: 3,
    total_resolved: 127,
    availability_status: "available",
    last_known_location: {
      lat: 40.758,
      lng: -73.9855,
      timestamp: "2026-01-13T10:30:00Z",
    },
    specializations: ["road", "lighting"],
  },
  {
    id: "5",
    full_name: "David Brown",
    role: "field_officer",
    email: "david@example.com",
    notification_enabled: true,
    points: 280,
    language_preference: "en",
    created_at: "2024-02-15T10:30:00Z",
    rating: 4.5,
    active_workload: 5,
    total_resolved: 89,
    availability_status: "busy",
    last_known_location: {
      lat: 40.7306,
      lng: -73.9352,
      timestamp: "2026-01-13T09:45:00Z",
    },
    specializations: ["waste", "water"],
  },
  {
    id: "6",
    full_name: "Emily Davis",
    role: "field_officer",
    email: "emily@example.com",
    notification_enabled: true,
    points: 720,
    language_preference: "en",
    created_at: "2024-01-05T08:00:00Z",
    rating: 4.9,
    active_workload: 2,
    total_resolved: 156,
    availability_status: "available",
    last_known_location: {
      lat: 40.7614,
      lng: -73.9776,
      timestamp: "2026-01-13T11:00:00Z",
    },
    specializations: ["road", "waste", "other"],
  },
  {
    id: "7",
    full_name: "Robert Martinez",
    role: "field_officer",
    email: "robert@example.com",
    notification_enabled: true,
    points: 410,
    language_preference: "en",
    created_at: "2024-03-01T07:30:00Z",
    rating: 4.3,
    active_workload: 4,
    total_resolved: 52,
    availability_status: "available",
    last_known_location: {
      lat: 40.7489,
      lng: -73.968,
      timestamp: "2026-01-13T10:15:00Z",
    },
    specializations: ["lighting", "water"],
  },
];

// Mock citizen reporter
const citizenReporter = {
  id: "1",
  full_name: "John Doe",
  role: "citizen",
  email: "john@example.com",
  notification_enabled: true,
  points: 450,
  language_preference: "en",
  created_at: "2024-01-15T10:00:00Z",
};

const citizenReporter2 = {
  id: "8",
  full_name: "Maria Garcia",
  role: "citizen",
  email: "maria@example.com",
  notification_enabled: true,
  points: 220,
  language_preference: "en",
  created_at: "2024-02-10T14:00:00Z",
};

// Enhanced issues with Ward Officer workflow scenarios
export const wardOfficerIssues = [
  // 1. Pending Verification - New issue awaiting WO review
  {
    id: "wo-1",
    ticket_id: "IMP-2026-0101",
    title: "Dangerous pothole causing accidents near Assi Ghat",
    description:
      "Large pothole on Assi Ghat Road near the ghat entry. Multiple two-wheelers have skidded. Urgent repair needed.",
    category: "road",
    status: "pending",
    internal_status: "pending_verification",
    severity: "high",
    priority_score: 38.5,
    upvotes: 24,
    photo_url:
      "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=800",
    additional_photos: [
      "https://images.pexels.com/photos/1029737/pexels-photo-1029737.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    latitude: 25.2887,
    longitude: 82.9876,
    address: "Assi Ghat Road, Assi Ghat, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-12T08:30:00Z",
    updated_at: "2026-01-12T08:30:00Z",
    reporter: citizenReporter,
    sla_due_date: "2026-01-15T08:30:00Z",
    is_overdue: false,
  },

  // 2. Pending Verification - Suspected duplicate
  {
    id: "wo-2",
    ticket_id: "IMP-2026-0102",
    title: "Pothole on Assi Ghat Road",
    description: "There is a pothole on Assi Ghat Road.",
    category: "road",
    status: "pending",
    internal_status: "pending_verification",
    severity: "medium",
    priority_score: 15.2,
    upvotes: 3,
    photo_url:
      "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.2889,
    longitude: 82.9874,
    address: "Near Assi Ghat, Varanasi, Uttar Pradesh, India",
    reported_by: "8",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-12T14:20:00Z",
    updated_at: "2026-01-12T14:20:00Z",
    reporter: citizenReporter2,
    sla_due_date: "2026-01-15T14:20:00Z",
    is_overdue: false,
    is_duplicate: true,
    duplicate_of: "wo-1",
  },

  // 3. Pending Verification - Out of jurisdiction
  {
    id: "wo-3",
    ticket_id: "IMP-2026-0103",
    title: "Broken streetlight on Ring Road Flyover",
    description:
      "Streetlight not working near the Ring Road Flyover stretch. Visibility is poor at night.",
    category: "lighting",
    status: "pending",
    internal_status: "pending_verification",
    severity: "medium",
    priority_score: 18.3,
    upvotes: 7,
    photo_url:
      "https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.3372,
    longitude: 82.9736,
    address: "Varanasi Ring Road Flyover, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-11T16:45:00Z",
    updated_at: "2026-01-11T16:45:00Z",
    reporter: citizenReporter,
    sla_due_date: "2026-01-14T16:45:00Z",
    is_overdue: false,
  },

  // 4. Pending Verification - Insufficient evidence
  {
    id: "wo-4",
    ticket_id: "IMP-2026-0104",
    title: "Water leak reported in Lanka area",
    description: "I saw water leaking near Lanka Market.",
    category: "water",
    status: "pending",
    internal_status: "pending_verification",
    severity: "low",
    priority_score: 8.5,
    upvotes: 1,
    latitude: 25.2796,
    longitude: 82.9991,
    address: "Lanka Market, Lanka, Varanasi, Uttar Pradesh, India",
    reported_by: "8",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-13T07:15:00Z",
    updated_at: "2026-01-13T07:15:00Z",
    reporter: citizenReporter2,
    sla_due_date: "2026-01-16T07:15:00Z",
    is_overdue: false,
  },

  // 5. Verified and In Progress
  {
    id: "wo-5",
    ticket_id: "IMP-2026-0105",
    title: "Overflowing garbage bins at Dashashwamedh Ghat",
    description:
      "Multiple garbage bins are completely full and overflowing near Dashashwamedh Ghat. Creating unsanitary conditions.",
    category: "waste",
    status: "in_progress",
    internal_status: "assigned",
    severity: "high",
    priority_score: 29.7,
    upvotes: 18,
    photo_url:
      "https://images.pexels.com/photos/2768961/pexels-photo-2768961.jpeg?auto=compress&cs=tinysrgb&w=800",
    additional_photos: [
      "https://images.pexels.com/photos/3850512/pexels-photo-3850512.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    latitude: 25.3071,
    longitude: 83.0107,
    address:
      "Dashashwamedh Ghat Road, Godowlia, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    assigned_to: "5",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-10T09:30:00Z",
    updated_at: "2026-01-11T14:20:00Z",
    reporter: citizenReporter,
    assignee: fieldOfficers[1],
    sla_due_date: "2026-01-13T09:30:00Z",
    is_overdue: true,
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },

  // 6. FO Marked Resolved - Pending WO Verification (with proof)
  {
    id: "wo-6",
    ticket_id: "IMP-2026-0106",
    title: "Broken streetlight on Sigra-Mahmoorganj Road",
    description:
      "Streetlight was out for 3 days on Sigra-Mahmoorganj Road. Area felt unsafe at night.",
    category: "lighting",
    status: "in_progress",
    internal_status: "fo_marked_resolved",
    severity: "medium",
    priority_score: 22.4,
    upvotes: 12,
    photo_url:
      "https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.3182,
    longitude: 82.9875,
    address: "Sigra Crossing, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    assigned_to: "4",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-08T18:00:00Z",
    updated_at: "2026-01-12T16:30:00Z",
    reporter: citizenReporter,
    assignee: fieldOfficers[0],
    sla_due_date: "2026-01-11T18:00:00Z",
    is_overdue: false,
    fo_completion_proof: [
      "https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    fo_location_trace: [
      { lat: 40.758, lng: -73.9855, timestamp: "2026-01-12T14:00:00Z" },
      { lat: 40.7585, lng: -73.9853, timestamp: "2026-01-12T14:15:00Z" },
      { lat: 40.7589, lng: -73.9851, timestamp: "2026-01-12T14:30:00Z" },
      { lat: 40.7589, lng: -73.9851, timestamp: "2026-01-12T16:30:00Z" },
    ],
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },

  // 7. FO Marked Resolved - Missing proof (should block verification)
  {
    id: "wo-7",
    ticket_id: "IMP-2026-0107",
    title: "Damaged footpath creating tripping hazard near BHU Gate",
    description:
      "Cracked and uneven footpath near BHU Main Gate. Several pedestrians almost tripped.",
    category: "road",
    status: "in_progress",
    internal_status: "fo_marked_resolved",
    severity: "medium",
    priority_score: 19.8,
    upvotes: 9,
    photo_url:
      "https://images.pexels.com/photos/257836/pexels-photo-257836.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.2672,
    longitude: 82.9912,
    address: "BHU Main Gate, Lanka, Varanasi, Uttar Pradesh, India",
    reported_by: "8",
    assigned_to: "6",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-09T11:20:00Z",
    updated_at: "2026-01-12T17:45:00Z",
    reporter: citizenReporter2,
    assignee: fieldOfficers[2],
    sla_due_date: "2026-01-12T11:20:00Z",
    is_overdue: false,
    fo_location_trace: [
      { lat: 40.753, lng: -73.982, timestamp: "2026-01-12T15:00:00Z" },
      { lat: 40.7532, lng: -73.9822, timestamp: "2026-01-12T15:30:00Z" },
    ],
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },

  // 8. Reopened Issue
  {
    id: "wo-8",
    ticket_id: "IMP-2026-0108",
    title: "Public water tap still not working near Ravindrapuri",
    description:
      "The tap was marked as fixed but it is still leaking and water pressure is very low.",
    category: "water",
    status: "in_progress",
    internal_status: "reopened",
    severity: "low",
    priority_score: 14.2,
    upvotes: 6,
    photo_url:
      "https://images.pexels.com/photos/3178938/pexels-photo-3178938.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.2824,
    longitude: 82.9862,
    address: "Ravindrapuri Colony, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    assigned_to: "7",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-05T10:00:00Z",
    updated_at: "2026-01-12T09:15:00Z",
    reporter: citizenReporter,
    assignee: fieldOfficers[3],
    sla_due_date: "2026-01-14T09:15:00Z",
    is_overdue: false,
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },

  // 9. Rejected - Spam
  {
    id: "wo-9",
    ticket_id: "IMP-2026-0109",
    title: "Test issue please ignore",
    description: "Testing the system.",
    category: "other",
    status: "rejected",
    internal_status: "pending_verification",
    severity: "low",
    priority_score: 2.1,
    upvotes: 0,
    latitude: 25.318,
    longitude: 82.989,
    address: "Sigra, Varanasi, Uttar Pradesh, India",
    reported_by: "8",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-11T13:00:00Z",
    updated_at: "2026-01-11T13:30:00Z",
    reporter: citizenReporter2,
    rejection_category: "spam",
    rejection_reason:
      "This appears to be a test submission and not a genuine civic issue.",
    rejection_notes:
      "User admitted to testing the system. No actual issue exists.",
  },

  // 10. Rejected - Duplicate
  {
    id: "wo-10",
    ticket_id: "IMP-2026-0110",
    title: "Another report about Assi Ghat pothole",
    description: "Pothole near Assi Ghat needs fixing.",
    category: "road",
    status: "rejected",
    internal_status: "pending_verification",
    severity: "medium",
    priority_score: 12.3,
    upvotes: 2,
    latitude: 25.2887,
    longitude: 82.9876,
    address: "Assi Ghat Road, Varanasi, Uttar Pradesh, India",
    reported_by: "8",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-12T15:00:00Z",
    updated_at: "2026-01-12T15:20:00Z",
    reporter: citizenReporter2,
    rejection_category: "duplicate",
    rejection_reason:
      "This issue has already been reported and is being addressed.",
    rejection_notes: "Duplicate of IMP-2026-0101. Same location and issue.",
    is_duplicate: true,
    duplicate_of: "wo-1",
  },

  // 11. Resolved
  {
    id: "wo-11",
    ticket_id: "IMP-2026-0111",
    title: "Graffiti on wall near Godowlia removed",
    description: "Offensive graffiti on the wall needed removal.",
    category: "other",
    status: "resolved",
    internal_status: "wo_verified",
    severity: "low",
    priority_score: 11.5,
    upvotes: 4,
    photo_url:
      "https://images.pexels.com/photos/1152851/pexels-photo-1152851.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.3096,
    longitude: 83.0069,
    address: "Godowlia Market Road, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    assigned_to: "6",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-07T09:00:00Z",
    updated_at: "2026-01-09T16:00:00Z",
    reporter: citizenReporter,
    assignee: fieldOfficers[2],
    wo_verified_at: "2026-01-09T16:00:00Z",
    fo_completion_proof: [
      "https://images.pexels.com/photos/1152851/pexels-photo-1152851.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },

  // 12. Rework Requested
  {
    id: "wo-12",
    ticket_id: "IMP-2026-0112",
    title: "Pothole repair incomplete near Pandeypur",
    description:
      "Pothole near Pandeypur Crossing was supposedly fixed but the patch is already breaking.",
    category: "road",
    status: "in_progress",
    internal_status: "assigned",
    severity: "medium",
    priority_score: 20.6,
    upvotes: 14,
    photo_url:
      "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=800",
    latitude: 25.3482,
    longitude: 82.987,
    address: "Pandeypur Crossing, Varanasi, Uttar Pradesh, India",
    reported_by: "1",
    assigned_to: "5",
    unit_officer_id: "3",
    is_anonymous: false,
    created_at: "2026-01-08T14:30:00Z",
    updated_at: "2026-01-12T11:00:00Z",
    reporter: citizenReporter,
    assignee: fieldOfficers[1],
    sla_due_date: "2026-01-11T14:30:00Z",
    is_overdue: true,
    rework_requested: true,
    rework_reason:
      "Initial repair was insufficient. Edges of patch are already crumbling. Needs complete rework.",
    authenticity_checked: {
      location_valid: true,
      evidence_sufficient: true,
      not_duplicate: true,
      within_jurisdiction: true,
    },
  },
];

export function getWardOfficerIssues() {
  return [...wardOfficerIssues];
}

export function getFieldOfficers() {
  return [...fieldOfficers];
}
